import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const popppins = Poppins({ 
    subsets: ["latin"],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${popppins.className} bg-my-secondary pt-28 pb-6 md:pt-[4.2rem] px-3 lg:px-4`}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
